### ISSUE TITLE
check that constants are the same in MOM and CICE5

### ISSUE THREAD

**Issue by aekiss** [OceansAus/access-om2#76] opened 2018-01-17 04:41 UTC
check that constants (e.g. Cp, Cd, Tocnfrz) are the same in both MOM and CICE5 code. Some but not all are in the name list files.

**Comment by aekiss** [comment] 2018-01-17 04:45
This is actually @PaulSpence's note.

**Comment by nichannah** [comment] 2018-10-24 06:14
This is a duplicate of https://github.com/OceansAus/access-om2/issues/22

**Closed by nichannah** 2018-10-24 06:14 UTC
